// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMm9rC1WeoO8KLN1cmsCdqeJkAETeNrTg',
    appId: '1:31793334558:web:0f87039cc291735570210f',
    messagingSenderId: '31793334558',
    projectId: 'jigu-h-ff716',
    authDomain: 'jigu-h-ff716.firebaseapp.com',
    storageBucket: 'jigu-h-ff716.appspot.com',
    measurementId: 'G-K31FNE97LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQmG5avS2AiGhEKx5sS8lNGwYKlSC7fw0',
    appId: '1:31793334558:android:d6f100f57e7ecd1a70210f',
    messagingSenderId: '31793334558',
    projectId: 'jigu-h-ff716',
    storageBucket: 'jigu-h-ff716.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEDDC-Bd-YR-Q6o1hOlufREt6Gp6T9k9o',
    appId: '1:31793334558:ios:69fc28c42477548e70210f',
    messagingSenderId: '31793334558',
    projectId: 'jigu-h-ff716',
    storageBucket: 'jigu-h-ff716.appspot.com',
    iosBundleId: 'com.example.jigu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEDDC-Bd-YR-Q6o1hOlufREt6Gp6T9k9o',
    appId: '1:31793334558:ios:b104ab60cdbfafec70210f',
    messagingSenderId: '31793334558',
    projectId: 'jigu-h-ff716',
    storageBucket: 'jigu-h-ff716.appspot.com',
    iosBundleId: 'com.example.jigu.RunnerTests',
  );
}
